### ISSUE TITLE
请问rabel如何安装？

### ISSUE THREAD

**Issue by robias** [daqing/rabel#83]
作者你好，我是一个非常新的新手，之前也只接触过php，目前想把rabel安装在我的vps上，但是因主站已关闭，找不到教程，请问如何实现呢？谢谢！

PS:程序真的是个好程序，貌似appletuan和mrmac也都使用的是这个程序，主站关闭有点遗憾。

**Comment by dd1994** [comment]
https://github.com/daqing/rabel/wiki/Rabel-%E5%AE%89%E8%A3%85%E6%8C%87%E5%8D%97

**Comment by dd1994** [comment]
https://github.com/daqing/rabel/wiki

**Comment by robias** [comment]
感谢，我看作者曾经开发到了2.0版本呢，可惜现在啥也看不到

**Comment by dd1994** [comment]
master 分支就是 2.0 alpha 版 https://github.com/daqing/rabel/blob/master/config/initializers/version.rb

**Comment by robias** [comment]
好的，另外，我现在的vps使用的是php+mysql，我看如果想用这个程序还得安装ruby，我再在我vps上安装ruby，对于其他网站有影响吗？谢谢

**Comment by dd1994** [comment]
当然没有影响
